// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9lEZxXDOkW2Y4s2G6-ZU6a9K1DMIK5qk',
    appId: '1:26452907944:web:e489db46ba0db4f6082f9d',
    messagingSenderId: '26452907944',
    projectId: 'lightforisrael-1ae3f',
    authDomain: 'lightforisrael-1ae3f.firebaseapp.com',
    storageBucket: 'lightforisrael-1ae3f.appspot.com',
    measurementId: 'G-K16YMJQ9XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhcuYa0uIPAtl0PIdCTuyzIjO5_CEOMlk',
    appId: '1:26452907944:android:3759124a441b5c96082f9d',
    messagingSenderId: '26452907944',
    projectId: 'lightforisrael-1ae3f',
    storageBucket: 'lightforisrael-1ae3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7uSemeQfoWPyzK6yjiqGayDcAJQm7KeY',
    appId: '1:26452907944:ios:1d2a345dc7beea58082f9d',
    messagingSenderId: '26452907944',
    projectId: 'lightforisrael-1ae3f',
    storageBucket: 'lightforisrael-1ae3f.appspot.com',
    iosClientId: '26452907944-msschj1e1n7soh4o8ukiripmthnfgsi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightforisrael',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7uSemeQfoWPyzK6yjiqGayDcAJQm7KeY',
    appId: '1:26452907944:ios:1d2a345dc7beea58082f9d',
    messagingSenderId: '26452907944',
    projectId: 'lightforisrael-1ae3f',
    storageBucket: 'lightforisrael-1ae3f.appspot.com',
    iosClientId: '26452907944-msschj1e1n7soh4o8ukiripmthnfgsi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightforisrael',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9lEZxXDOkW2Y4s2G6-ZU6a9K1DMIK5qk',
    appId: '1:26452907944:web:726b160a6eec97f4082f9d',
    messagingSenderId: '26452907944',
    projectId: 'lightforisrael-1ae3f',
    authDomain: 'lightforisrael-1ae3f.firebaseapp.com',
    storageBucket: 'lightforisrael-1ae3f.appspot.com',
    measurementId: 'G-P846QQPBTX',
  );

}